=== Outer-Wilds-New-Horizons/new-horizons/NewHorizons/Schemas/translation_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Translation Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "DialogueDictionary": {
      "type": "object",
      "description": "Translation table for dialogue",
      "additionalProperties": {
        "type": "string"
      }
    },
    "ShipLogDictionary": {
      "type": "object",
      "description": "Translation table for Ship Log (entries, facts, etc)",
      "additionalProperties": {
        "type": "string"
      }
    },
    "UIDictionary": {
      "type": "object",
      "description": "Translation table for UI elements",
      "additionalProperties": {
        "type": "string"
      }
    },
    "OtherDictionary": {
      "type": "object",
      "description": "Translation table for other text, will be taken verbatim without correcting CDATA",
      "additionalProperties": {
        "type": "string"
      }
    },
    "AchievementTranslations": {
      "type": "object",
      "description": "Translation table for achievements. The key is the unique ID of the achievement",
      "additionalProperties": {
        "$ref": "#/definitions/AchievementTranslationInfo"
      }
    },
    "$schema": {
      "type": "string",
      "description": "The schema to validate with"
    }
  },
  "definitions": {
    "AchievementTranslationInfo": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Name": {
          "type": "string",
          "description": "The name of the achievement."
        },
        "Description": {
          "type": "string",
          "description": "The short description for this achievement. (If showDescriptionNotAchieved is true in the achievement info this is shown AFTER the player gets the achievement)"
        },
        "DescriptionNotAchieved": {
          "type": "string",
          "description": "The short description for this achievement shown BEFORE the player gets the achievement. (Only if showDescriptionNotAchieved is true in the achievement info)"
        }
      }
    }
  },
  "$docs": {
    "title": "Translation Schema",
    "description": "Schema for a translation file in New Horizons"
  }
}

=== Outer-Wilds-New-Horizons/new-horizons/NewHorizons/Assets/translations/english.json
{
  "$schema": "https://raw.githubusercontent.com/outer-wilds-new-horizons/new-horizons/main/NewHorizons/Schemas/translation_schema.json",
  "DialogueDictionary": {
    "NEW_HORIZONS_WARP_DRIVE_DIALOGUE_1": "Your ship is now equipped with a warp drive!",
    "NEW_HORIZONS_WARP_DRIVE_DIALOGUE_2": "You can use the new \"Interstellar Mode\" page in the ship log to lock-on your autopilot to another star system.",
    "NEW_HORIZONS_WARP_DRIVE_DIALOGUE_3": "Then just buckle up and engage the autopilot to warp there!"
  },
  "UIDictionary": {
    "INSTALL_OUTER_WILDS_CHINESE_FONT_FIX": "What why is this message being shown when the language is not set to Chinese go report this bug!",
    "INTERSTELLAR_MODE": "Interstellar Mode",
    "FREQ_STATUE": "Nomai Statue",
    "FREQ_WARP_CORE": "Anti-Graviton Flux",
    "FREQ_UNKNOWN": "???",
    "ENGAGE_WARP_PROMPT": "Engage Warp To {0}",
    "WARP_LOCKED": "AUTOPILOT LOCKED TO:\n{0}",
    "LOCK_AUTOPILOT_WARP": "Lock Autopilot to Star System",
    "RICH_PRESENCE_EXPLORING": "Exploring {0}.",
    "RICH_PRESENCE_WARPING": "Warping to {0}.",
    "OUTDATED_VERSION_WARNING": "WARNING\n\nNew Horizons only works on version {0} or higher. You're on version {1}.\n\nPlease update your game or uninstall NH.",
    "JSON_FAILED_TO_LOAD": "Invalid file(s): {0}",
    "DEBUG_RAYCAST": "Raycast",
    "DEBUG_AIRBORNE": "Toggle Airborne Raycast",
    "DEBUG_AIRBORNE_Z": "Adjust Airborne Distance",
    "DEBUG_PLACE": "Place Object",
    "DEBUG_PLACE_TEXT": "Place Nomai Text",
    "DEBUG_UNDO": "Undo",
    "DEBUG_REDO": "Redo",
    "Vessel": "Vessel",
    "DLC_REQUIRED": "WARNING\n\nYou have addons (like {0}) installed which require the DLC but it is not enabled.\n\nYour mods may not function as intended.",
    "SolarSystem": "The Outer Wilds"
  },
  "OtherDictionary": {
    "NOMAI_SHUTTLE_COMPUTER": "The <![CDATA[<color=orange>shuttle</color>]]> is currently resting at <![CDATA[<color=lightblue>{0}</color>]]>.",
    "UNKNOWN_LANGUAGE_UNTRANSLATED": "<!> Untranslated unknown writing <!>",
    "KNOWN_LANGUAGE_UNTRANSLATED": "<!> Untranslated {0} writing <!>",
    "LANGUAGE_NAME_GHOSTBIRD": "Inhabitant"
  },
  "AchievementTranslations": {
    "NH_EATEN_OUTSIDE_BRAMBLE": {
      "Name": "Containment Breach",
      "Description": "Get eaten outside of Dark Bramble"
    },
    "NH_MULTIPLE_SYSTEM": {
      "Name": "Traveller",
      "Description": "Visit 5 unique star systems in a row."
    },
    "NH_NEW_FREQ": {
      "Name": "Anomalous Frequencies",
      "Description": "Discover a new frequency."
    },
    "NH_PROBE_LOST": {
      "Name": "Connection Lost",
      "Description": "Lose your little scout."
    },
    "NH_WARP_DRIVE": {
      "Name": "Lore Inaccurate",
      "Description": "Use your ship's warp drive."
    },
    "NH_VESSEL_WARP": {
      "Name": "Lore Accurate",
      "Description": "Warp to a star system using the Vessel."
    },
    "NH_RAFTING": {
      "Name": "The Raft and the Furious",
      "Description": "Go rafting."
    },
    "NH_SUCKED_INTO_LAVA_BY_TORNADO": {
      "Name": "Dieclone",
      "Description": "Get sucked into lava by a tornado."
    },
    "NH_TALK_TO_FIVE_CHARACTERS": {
      "Name": "Society",
      "Description": "Talk to 5 characters."
    }
  }
}

=== Outer-Wilds-New-Horizons/new-horizons/NewHorizons/Assets/translations/chinese_simple.json
{
  "$schema": "https://raw.githubusercontent.com/outer-wilds-new-horizons/new-horizons/main/NewHorizons/Schemas/translation_schema.json",
  "DialogueDictionary": {
    "NEW_HORIZONS_WARP_DRIVE_DIALOGUE_1": "你的宇宙飞船现在已经装备了跃迁驱动！",
    "NEW_HORIZONS_WARP_DRIVE_DIALOGUE_2": "你可以使用宇宙飞船日志中的\"恒星际模式\"来将你的自动驾驶目标锁定到另一个星系。",
    "NEW_HORIZONS_WARP_DRIVE_DIALOGUE_3": "之后只需要系好安全带并启动自动驾驶即可进行跃迁！"
  },
  "UIDictionary": {
    "INSTALL_OUTER_WILDS_CHINESE_FONT_FIX": "在享受故事之前，建议安装Outer Wilds Chinese Fix这个Mod来解决缺字问题。",
    "INTERSTELLAR_MODE": "恒星际模式",
    "FREQ_STATUE": "挪麦雕像",
    "FREQ_WARP_CORE": "反引力推进",
    "FREQ_UNKNOWN": "???",
    "ENGAGE_WARP_PROMPT": "将要跃迁到{0}",
    "WARP_LOCKED": "自动驾驶目标：\n{0}",
    "LOCK_AUTOPILOT_WARP": "锁定自动驾驶目标到该星系",
    "RICH_PRESENCE_EXPLORING": "探索 {0}.",
    "RICH_PRESENCE_WARPING": "正在跃迁到 {0}.",
    "OUTDATED_VERSION_WARNING": "警告\n\nNew Horizon模组只能工作在{0}或更高版本。你的当前版本是{1}。\n\n请更新你的游戏或卸载New Horizon模组",
    "JSON_FAILED_TO_LOAD": "无效文件: {0}",
    "DEBUG_RAYCAST": "投射",
    "DEBUG_PLACE": "放置对象",
    "DEBUG_PLACE_TEXT": "放置挪麦文字",
    "DEBUG_UNDO": "撤销",
    "DEBUG_REDO": "重做",
    "Vessel": "飞船"
  },
  "OtherDictionary": {
    "NOMAI_SHUTTLE_COMPUTER": "<![CDATA[<color=orange>穿梭机</color>]]>目前停泊在<![CDATA[<color=lightblue>{0}</color>]]>。",
    "UNKNOWN_LANGUAGE_UNTRANSLATED": "<!> 未翻译的未知文字 <!>",
    "KNOWN_LANGUAGE_UNTRANSLATED": "<!> 未翻译的{0}文字 <!>",
    "LANGUAGE_NAME_GHOSTBIRD": "居民"
  },
  "AchievementTranslations": {
    "NH_EATEN_OUTSIDE_BRAMBLE": {
      "Name": "收容失效",
      "Description": "在黑棘星外被吃掉。"
    },
    "NH_MULTIPLE_SYSTEM": {
      "Name": "星际旅者",
      "Description": "在一个循环中造访5个不同的星系。"
    },
    "NH_NEW_FREQ": {
      "Name": "异常频率",
      "Description": "发现一个新的频率。"
    },
    "NH_PROBE_LOST": {
      "Name": "连接丢失",
      "Description": "失去你的小侦察兵。"
    },
    "NH_WARP_DRIVE": {
      "Name": "自学成才",
      "Description": "使用宇宙飞船上的跃迁装置。"
    },
    "NH_VESSEL_WARP": {
      "Name": "有借无还",
      "Description": "在飞船进行跃迁以到达别的星系。"
    },
    "NH_RAFTING": {
      "Name": "木筏与激情",
      "Description": "进行一次漂流"
    },
    "NH_SUCKED_INTO_LAVA_BY_TORNADO": {
      "Name": "死亡旋风",
      "Description": "被龙卷风吸入岩浆之中。"
    },
    "NH_TALK_TO_FIVE_CHARACTERS": {
      "Name": "社交活动",
      "Description": "与五名角色对话。"
    }
  }
}

=== Outer-Wilds-New-Horizons/new-horizons/NewHorizons/Assets/translations/japanese.json
{
  "$schema": "https://raw.githubusercontent.com/xen-42/outer-wilds-new-horizons/main/NewHorizons/Schemas/translation_schema.json",
  "DialogueDictionary": {
    "NEW_HORIZONS_WARP_DRIVE_DIALOGUE_1": "探査艇にワープドライブが搭載されました！",
    "NEW_HORIZONS_WARP_DRIVE_DIALOGUE_2": "航行記録に新たに追加された“インターステラーモード”にて、別の星系をロックオンします。",
    "NEW_HORIZONS_WARP_DRIVE_DIALOGUE_3": "あとはシートベルトを締めて、それから自動操縦ボタンを押すだけでワープできます！"
  },
  "UIDictionary": {
    "INTERSTELLAR_MODE": "インターステラーモード",
    "FREQ_STATUE": "Nomai像",
    "FREQ_WARP_CORE": "反重力流束",
    "FREQ_UNKNOWN": "???",
    "ENGAGE_WARP_PROMPT": "{0}へのワープを開始",
    "WARP_LOCKED": "自動操縦のロックオン先：\n{0}",
    "LOCK_AUTOPILOT_WARP": "星系に自動操縦をロックオンする",
    "RICH_PRESENCE_EXPLORING": "{0}を探検中。",
    "RICH_PRESENCE_WARPING": "{0}へワープ中。",
    "OUTDATED_VERSION_WARNING": "警告\n\nNew Horizonsはバージョン{0}以上でのみ動作します。このOuter Wildsのバージョンは{1}です。\n\nOuter Wildsをアップデートするか、もしくはNew Horizonsをアンインストールしてください。",
    "JSON_FAILED_TO_LOAD": "無効なファイル：{0}",
    "DEBUG_RAYCAST": "Raycast",
    "DEBUG_PLACE": "Place Object",
    "DEBUG_PLACE_TEXT": "Place Nomai Text",
    "DEBUG_UNDO": "Undo",
    "DEBUG_REDO": "Redo",
    "Vessel": "船"
  },
  "OtherDictionary": {
    "NOMAI_SHUTTLE_COMPUTER": "<![CDATA[<color=orange>シャトル</color>]]>は現在<![CDATA[<color=lightblue>{0}</color>]]>に停泊している。",
    "UNKNOWN_LANGUAGE_UNTRANSLATED": "<!> 未訳の未知の文書 <!>",
    "KNOWN_LANGUAGE_UNTRANSLATED": "<!> 未訳の{0}の文書 <!>",
    "LANGUAGE_NAME_GHOSTBIRD": "住人"
  },
  "AchievementTranslations": {
    "NH_EATEN_OUTSIDE_BRAMBLE": {
      "Name": "収容違反",
      "Description": "闇のイバラの外で食べられる。"
    },
    "NH_MULTIPLE_SYSTEM": {
      "Name": "旅人",
      "Description": "5つの異なる星系を連続して訪れる。"
    },
    "NH_NEW_FREQ": {
      "Name": "異常な周波数",
      "Description": "新たな周波数を発見する。"
    },
    "NH_PROBE_LOST": {
      "Name": "失われた接続",
      "Description": "偵察機との接続が断たれる。"
    },
    "NH_WARP_DRIVE": {
      "Name": "不正確な伝承",
      "Description": "探査艇のワープドライブを使う。"
    },
    "NH_VESSEL_WARP": {
      "Name": "正確な伝承",
      "Description": "船でどこかの星系へワープする。"
    },
    "NH_RAFTING": {
      "Name": "イカダといかり",
      "Description": "イカダに乗る。"
    },
    "NH_SUCKED_INTO_LAVA_BY_TORNADO": {
      "Name": "ダイクロン",
      "Description": "竜巻で溶岩へと吸い込まれる。"
    },
    "NH_TALK_TO_FIVE_CHARACTERS": {
      "Name": "社会",
      "Description": "誰か5人と話す。"
    }
  }
}

=== Outer-Wilds-New-Horizons/new-horizons/NewHorizons/Assets/translations/french.json
{
  "$schema": "https://raw.githubusercontent.com/outer-wilds-new-horizons/new-horizons/main/NewHorizons/Schemas/translation_schema.json",
  "DialogueDictionary": {
    "NEW_HORIZONS_WARP_DRIVE_DIALOGUE_1": "Votre fusée est maintenant équipé d'un moteur de distorsion!",
    "NEW_HORIZONS_WARP_DRIVE_DIALOGUE_2": "Vous pouvez utiliser la nouvelle page \"Mode Interstellaire\" dans le journal de bord pour diriger votre pilote automatique vers un autre système solaire",
    "NEW_HORIZONS_WARP_DRIVE_DIALOGUE_3": "Ensuite, bouclez votre ceinture et engagez le pilote automatique pour y aller!"
  },
  "UIDictionary": {
    "INTERSTELLAR_MODE": "Mode interstellaire",
    "FREQ_STATUE": "Statue Nomaï",
    "FREQ_WARP_CORE": "Flux Anti-Gravitonique",
    "FREQ_UNKNOWN": "???",
    "ENGAGE_WARP_PROMPT": "Engagez la distorsion vers {0}",
    "WARP_LOCKED": "PILOTE AUTOMATIQUE VISÉ SUR:\n{0}",
    "LOCK_AUTOPILOT_WARP": "Visez le pilote automatique",
    "RICH_PRESENCE_EXPLORING": "En explorant {0}.",
    "RICH_PRESENCE_WARPING": "En route vers {0}.",
    "OUTDATED_VERSION_WARNING": "AVERTISSEMENT\n\nNew Horizons fonctionne seulement sur la version {0} ou plus récente. Vous êtes sur la version {1}.\n\nVeuillez mettre à jour votre jeu ou désinstaller NH.",
    "JSON_FAILED_TO_LOAD": "Fichier(s) invalide(s): {0}",
    "Vessel": "Vaisseau",
    "DLC_REQUIRED": "AVERTISSEMENT\n\nVous avez installé des addons (par exemple, {0}) qui nécessitent le DLC mais il n'est pas activé.\n\nVos mods peuvent ne pas fonctionner."
  },
  "OtherDictionary": {
    "NOMAI_SHUTTLE_COMPUTER": "La <![CDATA[<color=orange>navette</color>]]> est actuellement stationnée sur la <![CDATA[<color=lightblue>{0}</color>]]>.",
    "UNKNOWN_LANGUAGE_UNTRANSLATED": "<!> Écrit inconnu non traduit <!>",
    "KNOWN_LANGUAGE_UNTRANSLATED": "<!> Écrit {0} non traduit <!>",
    "LANGUAGE_NAME_GHOSTBIRD": "habitant"
  },
  "AchievementTranslations": {
    "NH_EATEN_OUTSIDE_BRAMBLE": {
      "Name": "Brèche de confinement",
      "Description": "Soyez mangé à l'extérieur de Sombronces."
    },
    "NH_MULTIPLE_SYSTEM": {
      "Name": "Le voyageur",
      "Description": "Visitez 5 systèmes solaires uniques d'affilée."
    },
    "NH_NEW_FREQ": {
      "Name": "Fréquence anormale",
      "Description": "Découvrez une nouvelle fréquence."
    },
    "NH_PROBE_LOST": {
      "Name": "Connexion perdue",
      "Description": "Perdez votre lance-guetteur."
    },
    "NH_WARP_DRIVE": {
      "Name": "En désaccord avec l'histoire.",
      "Description": "Utilisez le moteur de distorsion de votre fusée."
    },
    "NH_VESSEL_WARP": {
      "Name": "En accord avec l'histoire.",
      "Description": "Voyagez vers un autre système solaire avec le Vaissau."
    }
  }
}

=== Outer-Wilds-New-Horizons/new-horizons/NewHorizons/Assets/translations/spanish_la.json
{
  "$schema": "https://raw.githubusercontent.com/outer-wilds-new-horizons/new-horizons/main/NewHorizons/Schemas/translation_schema.json",
  "DialogueDictionary": {
    "NEW_HORIZONS_WARP_DRIVE_DIALOGUE_1": "¡Tu nave ahora tiene un motor de curvatura!",
    "NEW_HORIZONS_WARP_DRIVE_DIALOGUE_2": "Puedes usar la nueva página de \"modo interestelar\" en el registro de la nave para fijar el piloto automático a otro sistema solar.",
    "NEW_HORIZONS_WARP_DRIVE_DIALOGUE_3": "¡Después abróchate el cinturón y enciende el piloto automático para teletransportarte allí!"
  },
  "UIDictionary": {
    "INTERSTELLAR_MODE": "Modo Interestelar",
    "FREQ_STATUE": "Estatua Nomai",
    "FREQ_WARP_CORE": "Flujo De Anti-Gravitones",
    "FREQ_UNKNOWN": "???",
    "ENGAGE_WARP_PROMPT": "Iniciar teletransporte a {0}",
    "WARP_LOCKED": "Piloto automático fijado en:\n{0}",
    "Vessel": "Nave"
  },
  "OtherDictionary": {
    "NOMAI_SHUTTLE_COMPUTER": "El <![CDATA[<color=orange>transbordador/color>]]> se encuentra posado sobre la <![CDATA[<color=lightblue>{0}</color>]]>.",
    "UNKNOWN_LANGUAGE_UNTRANSLATED": "<!> Texto desconocido sin traducir <!>",
    "KNOWN_LANGUAGE_UNTRANSLATED": "<!> Texto {0} sin traducir <!>",
    "LANGUAGE_NAME_GHOSTBIRD": "habitant"
  },
  "AchievementTranslations": {
    "NH_EATEN_OUTSIDE_BRAMBLE": {
      "Name": "Brecha de contención",
      "Description": "Sé devorado fuera de Espinoscuro"
    },
    "NH_MULTIPLE_SYSTEM": {
      "Name": "Viajero",
      "Description": "Visita 5 sistemas estelares seguidos"
    },
    "NH_NEW_FREQ": {
      "Name": "Frecuencias Anómalas",
      "Description": "Descubre una nueva frecuencia"
    },
    "NH_PROBE_LOST": {
      "Name": "Conexión Perdida",
      "Description": "Pierde tu miniexplorador"
    },
    "NH_WARP_DRIVE": {
      "Name": "Inexacto al Lore",
      "Description": "Usa el motor de distorsiones de tu nave"
    },
    "NH_VESSEL_WARP": {
      "Name": "Como lo dice la ciencia",
      "Description": "Teletranspórtate a otro sistema estelar usando la Nave"
    }
  }
}

=== Outer-Wilds-New-Horizons/new-horizons/NewHorizons/Assets/translations/portuguese_br.json
{
  "$schema": "https://raw.githubusercontent.com/outer-wilds-new-horizons/new-horizons/main/NewHorizons/Schemas/translation_schema.json",
  "DialogueDictionary": {
    "NEW_HORIZONS_WARP_DRIVE_DIALOGUE_1": "Sua nave agora está equipada com uma unidade de translocação!",
    "NEW_HORIZONS_WARP_DRIVE_DIALOGUE_2": "Você pode usar a nova aba \"Modo Interestelar\" no diário de bordo de sua nave para ajustar o piloto automático rumo a outro sistema solar.",
    "NEW_HORIZONS_WARP_DRIVE_DIALOGUE_3": "Então é só acionar o piloto automático e relaxar!"
  },
  "UIDictionary": {
    "INTERSTELLAR_MODE": "Modo Interestelar",
    "FREQ_STATUE": "Estátua Nomai",
    "FREQ_WARP_CORE": "Fluxo Anti-Gravitacional",
    "FREQ_UNKNOWN": "???",
    "ENGAGE_WARP_PROMPT": "Acionar translocação a {0}",
    "WARP_LOCKED": "PILOTO AUTOMÁTICO AJUSTADO PARA:\n{0}",
    "LOCK_AUTOPILOT_WARP": "Ajustar Piloto Automático para sistema solar",
    "RICH_PRESENCE_EXPLORING": "Explorando {0}.",
    "RICH_PRESENCE_WARPING": "Translocando para {0}.",
    "OUTDATED_VERSION_WARNING": "AVISO\n\nA mod New Horizons funciona apenas na versão {0} ou superior. Você está usando a versão {1}.\n\nAtualize Outer Wilds ou desinstale NH.",
    "JSON_FAILED_TO_LOAD": "Arquivo(s) inválido(s): {0}",
    "DEBUG_RAYCAST": "Raycast",
    "DEBUG_PLACE": "Posicionar objeto",
    "DEBUG_PLACE_TEXT": "Colocar texto Nomai",
    "DEBUG_UNDO": "Desfazer",
    "DEBUG_REDO": "Refazer",
    "Vessel": "Hospedeiro",
    "DLC_REQUIRED": "AVISO\n\nVocê tem addons (ex. {0}) instalados que requerem a DLC, mas a mesma não está habilitada.\n\nSuas mods podem não funcionar como esperado."
  },
  "OtherDictionary": {
    "NOMAI_SHUTTLE_COMPUTER": "A <![CDATA[<color=orange>exploradora</color>]]> está repousando por hora em: <![CDATA[<color=lightblue>{0}</color>]]>.",
    "UNKNOWN_LANGUAGE_UNTRANSLATED": "<!> Escrito desconhecido não traduzido <!>",
    "KNOWN_LANGUAGE_UNTRANSLATED": "<!> Escrito {0} não traduzido <!>",
    "LANGUAGE_NAME_GHOSTBIRD": "Habitante"
  },
  "AchievementTranslations": {
    "NH_EATEN_OUTSIDE_BRAMBLE": {
      "Name": "Fenda de Contenção",
      "Description": "Seja devorado fora dos limites de Abrolho Sombrio"
    },
    "NH_MULTIPLE_SYSTEM": {
      "Name": "Viajante",
      "Description": "Visite 5 sistemas solares seguidos."
    },
    "NH_NEW_FREQ": {
      "Name": "Frequências Anômalas",
      "Description": "Descubra uma nova frequência."
    },
    "NH_PROBE_LOST": {
      "Name": "Conexão Perdida",
      "Description": "Perca seu pequeno batedor."
    },
    "NH_WARP_DRIVE": {
      "Name": "História Mal Contada",
      "Description": "Use a unidade de translocação da nave."
    },
    "NH_VESSEL_WARP": {
      "Name": "História Acertada",
      "Description": "Transloque para um sistema estelar usando o Hospedeiro."
    },
    "NH_RAFTING": {
      "Name": "A Jangada e os Furiosos",
      "Description": "Dê um rolé de jangada."
    },
    "NH_SUCKED_INTO_LAVA_BY_TORNADO": {
      "Name": "Dieclone",
      "Description": "Seja sugado na lava por um tornado."
    },
    "NH_TALK_TO_FIVE_CHARACTERS": {
      "Name": "Social",
      "Description": "Converse com 5 personagens."
    }
  }
}
